version: 2

models:
  - name: daily_user_count
    description: "Daily user count"
    columns:
      - name: date
        tests: [unique, not_null]

  - name: weekly_user_count
    description: "Weekly user count"
    columns:
      - name: week
        tests: [unique, not_null]

  - name: monthly_user_count
    description: "Monthly user count"
    columns:
      - name: month
        tests: [unique, not_null]